version: "3.7"
services:
    nginx:
        image: nginx:stable
        ports:
            - ${NGINX_PORT:-88}:80
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs:/var/log/nginx
        environment:
            NGINX_HOST: localhost
            NGINX_PORT: 8080
        restart: on-failure
        links:
            - app
        depends_on:
            - app

    postgres:
        image: postgres:13
        restart: on-failure
        environment:
            - POSTGRES_DB=laravel
            - POSTGRES_PASSWORD=aKL1dmFxs10x
        ports:
            - 5432:5432
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
            - ./postgresql/postgres-init.sql:/docker-entrypoint

    app:
        build: ./php
        volumes:
            - ./:/var/www
        restart: on-failure
        environment:
            OPCACHE_ENABLE: ${OPCACHE_ENABLE:-true}
        links:
            - postgres
        depends_on:
            - postgres
